# Use postgres/example user/password credentials
version: "3.1"

networks:
  dev-code_sharing-network:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - dev-code_sharing-network

  backend:
    image: code_sharing-backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
      - 3001:3001
    depends_on:
      - "db"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: "bash ./scripts/setup-and-run.sh"
    container_name: code_sharing_backend
    env_file:
      - ./backend/.env
    networks:
      - dev-code_sharing-network

  frontend:
      image: code_sharing-frontend
      build: ./frontend
      restart: always
      ports:
        - 80:3000
      depends_on: 
        - "backend"
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
      container_name: code_sharing_frontend
      env_file:
        - ./frontend/.env
      networks: 
        - dev-code_sharing-network
