CREATE TABLE IF NOT EXISTS collaborators (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  instance_id INTEGER,
  permission_id INTEGER,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP DEFAULT now() NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id),
  CONSTRAINT fk_instance
    FOREIGN KEY(instance_id)
      REFERENCES instances(id),
  CONSTRAINT fk_permission
    FOREIGN KEY(permission_id)
      REFERENCES permissions(id)
);